# hash:sha256:88aa538aef25dc4cdb126a81cfdb8475ebfb03f9daf1b91999070df75cd19efe
FROM registry.codeocean.com/codeocean/miniconda3:4.8.2-python3.8-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    colorama==0.4.3 \
    h5py==3.1.0 \
    keras==2.6.0 \
    matplotlib==3.3.4 \
    numpy==1.19.2 \
    openpyxl==3.0.6 \
    pandas==1.2.3 \
    pyswarms==1.3.0 \
    scikit-learn==0.22.1 \
    tensorflow==2.6.0 \
    xgboost==1.3.3
